version: "3"
services:
  reverse-proxy:
    image: traefik:v2.3.4
    command: --api.insecure=true --providers.docker
    ports:
      - "8080:8080"
      - "80:80"
      - "443:443"
    
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/traefik.yml

    environment:
      - DUCKDNS_TOKEN=<REDACTED>

  mesa-simulation:
    build: 
      context: .
      dockerfile: "Dockerfile2"
    image: mesa-simulation:dev
    volumes:
      - .:/opt/mesa
        #ports:
        #- "9061-9161:9061"
    deploy:
      replicas: 40
    labels:
      - "traefik.http.routers.mesa-simulation.rule=Host(`timothymardesen.duckdns.org`)"
      - "traefik.port=9061"
      - "traefik.enable=true"
      - "traefik.http.routers.mesa-simulation.entrypoints=websecure"
      - "traefik.http.routers.mesa-simulation.tls=true"
      - "traefik.http.routers.mesa-simulation.tls.certresolver=le"
      - "traefik.frontend.rule=Host:mesa-simulation"
