providers:
  docker:
          #endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: public

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    forwardedHeaders:
      insecure: true
    http:
      tls:
        certResolver: le

certificatesResolvers:
  le:
    acme:
      email: "timothymardesen@yahoo.com"
      storage: "/acme.json"
      dnsChallenge:
        provider: "duckdns"
        delayBeforeCheck: 0
      httpChallenge:
        entryPoint: web

api:
  insecure: true
  dashboard: true

metrics:
  influxDB:
    address: 192.168.2.14:8089
    protocol: udp
    username: "admin"
    password: "admin"
    database: "mesa-simulation"

log:
  level: info
